# Compilamos el código de C++

In [96]:
!cd .. && mkdir build
!cd ../build/ && rm -rf *
!cd ../build && cmake \
  -DPYTHON_EXECUTABLE="$(which python)" \
  -DCMAKE_BUILD_TYPE=Release ..
!cd ../build && make install

mkdir: cannot create directory ‘build’: File exists
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release mode
-- Found PythonInterp: /home/fyulita/.virtualenvs/scienv/bin/python (found version "3.8.3") 
-- Found PythonLibs: /usr/lib/libpython3.8.so
-- pybind11 v2.2.4
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMAKE_INSTALL_PREFIX=/home/fyulita/Documents/UBA/2020-1C/Metodos Numericos/Material/Laboratorio/tp02
-

In [97]:
!pwd
!python --version
import metnum

/home/fyulita/Documents/UBA/2020-1C/Metodos Numericos/Material/Laboratorio/tp02/notebooks
Python 3.8.3


# Testeamos el cálculo de autovalores y autovectores

*Obs.: Por lo visto hay un tema con los signos de los autovectores.*

In [47]:
import numpy as np

In [52]:
A = np.array([
    [2, 0],
    [0, 1]
])
lambdas_exp = np.array([2, 1])
V_exp = np.array([
    [1, 0],
    [0, 1]
])

lambdas, V = metnum.get_first_eigenvalues(A, 2)

print(lambdas)
print(V)

assert np.allclose(lambdas_exp, lambdas)
assert np.allclose(V_exp, V)

[2. 1.]
[[ 1.00000000e+00  2.22615677e-16]
 [-1.11307838e-16  1.00000000e+00]]


In [54]:
B = np.array([
    [2, 1],
    [1, 1]
])
lambdas_exp = np.array([(3 + np.sqrt(5)) / 2, (3 - np.sqrt(5)) / 2])
V_exp = np.array([
    [(1 + np.sqrt(5)) / (2 * np.sqrt(1 + ((1 + np.sqrt(5)) / 2) ** 2)), (1 - np.sqrt(5)) / (2 * np.sqrt(1 + ((1 - np.sqrt(5)) / 2) ** 2))],
    [1 / np.sqrt(1 + ((1 + np.sqrt(5)) / 2) ** 2), 1 / np.sqrt(1 + ((1 - np.sqrt(5)) / 2) ** 2)]
])

lambdas, V = metnum.get_first_eigenvalues(B, 2)

print(lambdas)
print(V)

assert np.allclose(lambdas_exp, lambdas)
assert np.allclose(V_exp, V)

[2.61803399 0.38196601]
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


# Testeamos PCA

## Cálculo de Covarianza

In [98]:
import numpy as np

alpha = 30
pca = metnum.PCA(alpha)

In [105]:
A = np.array([
    [64, 580, 29],
    [66, 570, 33],
    [68, 590, 37],
    [69, 660, 46],
    [73, 600, 55]
])

A_expected = np.array([
    [11.5, 50, 34.75],
    [50, 1250, 205],
    [34.75, 205, 110]
])

pca.fit(A)
ans = pca.transform(np.eye(3))

print(ans)

[[  11.5    50.     34.75]
 [  50.   1250.    205.  ]
 [  34.75  205.    110.  ]]
